import { useEffect, useState } from 'react';
import DataTable from '../components/common/DataTable';
import FormModal from '../components/common/FormModal';
import ConfirmDialog from '../components/common/ConfirmDialog';
import LoadingSpinner from '../components/common/LoadingSpinner';
import PageHeader from '../components/common/PageHeader';
import { api, getErrorMessage } from '../services/api';

const emptyItem = { supply_id: '', quantity: 1 };
export default function DistributionsPage() {
  const [rows, setRows] = useState([]); const [requests, setRequests] = useState([]); const [supplies, setSupplies] = useState([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [form, setForm] = useState({ request_id: '', notes: '', items: [{ ...emptyItem }] }); const [removeTarget, setRemoveTarget] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); try { const [distributionResponse, requestResponse, supplyResponse] = await Promise.all([api.distributions.list(), api.requests.list(), api.supplies.list()]); setRows(distributionResponse.data.data || []); setRequests((requestResponse.data.data || []).filter((request) => request.status === 'Approved')); setSupplies(supplyResponse.data.data || []); } catch (err) { setError(getErrorMessage(err)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const setItem = (index, key, value) => setForm({ ...form, items: form.items.map((item, i) => i === index ? { ...item, [key]: value } : item) });
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { const payload = { request_id: Number(form.request_id), notes: form.notes || null, items: form.items.map((item) => ({ supply_id: Number(item.supply_id), quantity: Number(item.quantity) })) }; const { data } = await api.distributions.create(payload); setNotice(data.message); setOpen(false); setForm({ request_id: '', notes: '', items: [{ ...emptyItem }] }); load(); } catch (err) { setError(getErrorMessage(err)); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { const { data } = await api.distributions.remove(removeTarget.id); setNotice(data.message); setRemoveTarget(null); load(); } catch (err) { setError(getErrorMessage(err)); } finally { setBusy(false); } };
  const columns = [{ label: 'ID', key: 'id' }, { label: 'Request', key: 'request_id' }, { label: 'Distributed by', key: 'distributed_by_name' }, { label: 'Date', render: (row) => new Date(row.distribution_date).toLocaleString() }, { label: 'Notes', render: (row) => row.notes || '—' }, { label: 'Actions', render: (row) => <button className="btn btn-sm btn-outline-danger" onClick={() => setRemoveTarget(row)}>Reverse & Delete</button> }];
  return <><PageHeader title="Distributions" description="Record approved relief distributions and track inventory movement." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>Create Distribution</button>} />{error && <div className="alert alert-danger alert-dismissible">{error}<button className="btn-close" onClick={() => setError('')} /></div>}{notice && <div className="alert alert-success alert-dismissible">{notice}<button className="btn-close" onClick={() => setNotice('')} /></div>}<div className="card border-0 shadow-sm"><div className="card-body">{loading ? <LoadingSpinner /> : <DataTable rows={rows} columns={columns} searchPlaceholder="Search distributions..." />}</div></div><FormModal show={open} title="Create Distribution" onClose={() => setOpen(false)} onSubmit={submit} submitting={busy} submitLabel="Create Distribution"><div className="mb-3"><label className="form-label">Approved request</label><select className="form-select" value={form.request_id} onChange={(e) => setForm({ ...form, request_id: e.target.value })} required><option value="">Choose an approved request</option>{requests.map((request) => <option value={request.id} key={request.id}>#{request.id} — {request.user_name} ({request.shelter_name})</option>)}</select></div><div className="mb-3"><label className="form-label">Notes <span className="text-secondary">(optional)</span></label><textarea rows="2" className="form-control" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div><label className="form-label">Supply items</label>{form.items.map((item, index) => <div className="row g-2 align-items-end mb-2" key={index}><div className="col-md-7"><select className="form-select" value={item.supply_id} onChange={(e) => setItem(index, 'supply_id', e.target.value)} required><option value="">Choose supply</option>{supplies.map((supply) => <option key={supply.id} value={supply.id}>{supply.name} ({supply.quantity} {supply.unit})</option>)}</select></div><div className="col-md-3"><input className="form-control" type="number" min="1" value={item.quantity} onChange={(e) => setItem(index, 'quantity', e.target.value)} required /></div><div className="col-md-2">{form.items.length > 1 && <button type="button" className="btn btn-outline-danger w-100" onClick={() => setForm({ ...form, items: form.items.filter((_, i) => i !== index) })}>Remove</button>}</div></div>)}<button type="button" className="btn btn-sm btn-outline-primary" onClick={() => setForm({ ...form, items: [...form.items, { ...emptyItem }] })}>+ Add supply item</button></FormModal><ConfirmDialog show={Boolean(removeTarget)} title="Reverse Distribution" message="Delete this distribution? Inventory will be restored and the request returned to Approved." onClose={() => setRemoveTarget(null)} onConfirm={remove} busy={busy} /></>;
}
