import { Link, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { api, getErrorMessage } from '../services/api';

const initial = { full_name: '', email: '', password: '', phone: '', address: '' };
export default function RegisterPage() {
  const navigate = useNavigate(); const [form, setForm] = useState(initial); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); setBusy(true); try { const { data } = await api.auth.register(form); setSuccess(data.message || 'Registration successful. Please sign in.'); setTimeout(() => navigate('/login'), 900); } catch (err) { setError(getErrorMessage(err)); } finally { setBusy(false); } };
  return <div className="auth-page"><div className="auth-card card border-0 shadow"><div className="card-body p-4 p-md-5"><div className="text-center mb-4"><div className="brand-mark">DR</div><h1 className="h3 mt-3">Victim registration</h1><p className="text-secondary">Create an account to request relief assistance.</p></div>{error && <div className="alert alert-danger">{error}</div>}{success && <div className="alert alert-success">{success}</div>}<form onSubmit={submit}><div className="row"><div className="col-md-6 mb-3"><label className="form-label">Full name</label><input className="form-control" value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} required /></div><div className="col-md-6 mb-3"><label className="form-label">Phone</label><input className="form-control" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} required /></div></div><div className="mb-3"><label className="form-label">Email</label><input type="email" className="form-control" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></div><div className="mb-3"><label className="form-label">Password</label><input type="password" className="form-control" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} minLength="6" required /></div><div className="mb-4"><label className="form-label">Address</label><textarea className="form-control" rows="2" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} required /></div><button className="btn btn-primary w-100" disabled={busy}>{busy ? 'Registering...' : 'Register'}</button></form><p className="text-center small mt-4 mb-0">Already registered? <Link to="/login">Sign in</Link></p></div></div></div>;
}
