import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import DataTable from '../components/common/DataTable';
import FormModal from '../components/common/FormModal';
import ConfirmDialog from '../components/common/ConfirmDialog';
import LoadingSpinner from '../components/common/LoadingSpinner';
import PageHeader from '../components/common/PageHeader';
import StatusBadge from '../components/common/StatusBadge';
import { api, getErrorMessage } from '../services/api';

export default function RequestsPage() {
  const { user } = useAuth(); const admin = user?.role === 'admin';
  const [rows, setRows] = useState([]); const [shelters, setShelters] = useState([]); const [loading, setLoading] = useState(true); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState({ shelter_id: '', priority: 'Medium', remarks: '' }); const [removeTarget, setRemoveTarget] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); try { const response = await api.requests.list(); setRows(response.data.data || []); if (!admin) { const shelterResponse = await api.shelters.list(); setShelters(shelterResponse.data.data || []); } } catch (err) { setError(getErrorMessage(err)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [admin]);
  const create = async (event) => { event.preventDefault(); setBusy(true); try { const { data } = await api.requests.create({ ...form, shelter_id: Number(form.shelter_id) }); setNotice(data.message); setFormOpen(false); setForm({ shelter_id: '', priority: 'Medium', remarks: '' }); load(); } catch (err) { setError(getErrorMessage(err)); } finally { setBusy(false); } };
  const updateStatus = async (id, status) => { try { const { data } = await api.requests.updateStatus(id, status); setNotice(data.message); load(); } catch (err) { setError(getErrorMessage(err)); } };
  const remove = async () => { setBusy(true); try { const { data } = await api.requests.remove(removeTarget.id); setNotice(data.message); setRemoveTarget(null); load(); } catch (err) { setError(getErrorMessage(err)); } finally { setBusy(false); } };
  const columns = [{ label: 'ID', key: 'id' }, ...(admin ? [{ label: 'Victim', key: 'user_name' }] : []), { label: 'Shelter', key: 'shelter_name' }, { label: 'Priority', render: (row) => <StatusBadge value={row.priority} /> }, { label: 'Status', render: (row) => <StatusBadge value={row.status} /> }, { label: 'Remarks', render: (row) => row.remarks || '—' }, ...(admin ? [{ label: 'Actions', render: (row) => <div className="d-flex gap-1 align-items-center"><select className="form-select form-select-sm" value={row.status} onChange={(e) => updateStatus(row.id, e.target.value)}><option>Pending</option><option>Approved</option><option>Rejected</option><option>Distributed</option></select><button className="btn btn-sm btn-outline-danger" onClick={() => setRemoveTarget(row)}>Delete</button></div> }] : [])];
  return <><PageHeader title={admin ? 'Relief Requests' : 'My Relief Requests'} description={admin ? 'Review and update victim relief requests.' : 'Submit and follow your relief assistance requests.'} action={!admin && <button className="btn btn-primary" onClick={() => setFormOpen(true)}>Create Request</button>} />{error && <div className="alert alert-danger alert-dismissible">{error}<button className="btn-close" onClick={() => setError('')} /></div>}{notice && <div className="alert alert-success alert-dismissible">{notice}<button className="btn-close" onClick={() => setNotice('')} /></div>}<div className="card border-0 shadow-sm"><div className="card-body">{loading ? <LoadingSpinner /> : <DataTable rows={rows} columns={columns} searchPlaceholder="Search relief requests..." />}</div></div><FormModal show={formOpen} title="Create Relief Request" onClose={() => setFormOpen(false)} onSubmit={create} submitting={busy} submitLabel="Submit Request"><div className="mb-3"><label className="form-label">Shelter</label><select className="form-select" value={form.shelter_id} onChange={(e) => setForm({ ...form, shelter_id: e.target.value })} required><option value="">Choose a shelter</option>{shelters.map((shelter) => <option value={shelter.id} key={shelter.id}>{shelter.name} — {shelter.location}</option>)}</select></div><div className="mb-3"><label className="form-label">Priority</label><select className="form-select" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option>Low</option><option>Medium</option><option>High</option></select></div><div><label className="form-label">Remarks <span className="text-secondary">(optional)</span></label><textarea className="form-control" rows="4" value={form.remarks} onChange={(e) => setForm({ ...form, remarks: e.target.value })} /></div></FormModal><ConfirmDialog show={Boolean(removeTarget)} title="Delete Relief Request" message="Delete this relief request?" onClose={() => setRemoveTarget(null)} onConfirm={remove} busy={busy} /></>;
}
