import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import DataTable from '../components/common/DataTable';
import FormModal from '../components/common/FormModal';
import ConfirmDialog from '../components/common/ConfirmDialog';
import LoadingSpinner from '../components/common/LoadingSpinner';
import PageHeader from '../components/common/PageHeader';
import { getErrorMessage } from '../services/api';

export default function ResourceManager({ title, description, apiResource, fields, columns, itemName }) {
  const { user } = useAuth(); const canManage = user?.role === 'admin';
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [editing, setEditing] = useState(null); const [removeTarget, setRemoveTarget] = useState(null); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); try { const { data } = await apiResource.list(); setRows(data.data || []); } catch (err) { setError(getErrorMessage(err)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const payload = {}; fields.forEach((field) => { let value = editing[field.name]; if (field.type === 'number') value = Number(value); payload[field.name] = value === '' && field.optional ? null : value; }); const { data } = editing.id ? await apiResource.update(editing.id, payload) : await apiResource.create(payload); setNotice(data.message || `${itemName} saved successfully.`); setEditing(null); load(); } catch (err) { setError(getErrorMessage(err)); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { const { data } = await apiResource.remove(removeTarget.id); setNotice(data.message || `${itemName} deleted successfully.`); setRemoveTarget(null); load(); } catch (err) { setError(getErrorMessage(err)); setRemoveTarget(null); } finally { setBusy(false); } };
  const actionColumns = canManage ? [...columns, { label: 'Actions', render: (row) => <div className="btn-group btn-group-sm"><button className="btn btn-outline-primary" onClick={() => setEditing({ ...row })}>Edit</button><button className="btn btn-outline-danger" onClick={() => setRemoveTarget(row)}>Delete</button></div> }] : columns;
  return <><PageHeader title={title} description={description} action={canManage && <button className="btn btn-primary" onClick={() => setEditing(fields.reduce((form, field) => ({ ...form, [field.name]: field.defaultValue ?? '' }), {}))}>Add {itemName}</button>} />{error && <div className="alert alert-danger alert-dismissible">{error}<button className="btn-close" onClick={() => setError('')} /></div>}{notice && <div className="alert alert-success alert-dismissible">{notice}<button className="btn-close" onClick={() => setNotice('')} /></div>}<div className="card border-0 shadow-sm"><div className="card-body">{loading ? <LoadingSpinner /> : <DataTable rows={rows} columns={actionColumns} searchPlaceholder={`Search ${itemName.toLowerCase()}s...`} />}</div></div><FormModal show={Boolean(editing)} title={`${editing?.id ? 'Edit' : 'Add'} ${itemName}`} onClose={() => setEditing(null)} onSubmit={save} submitting={busy}>{fields.map((field) => <div className="mb-3" key={field.name}><label className="form-label">{field.label}</label>{field.type === 'textarea' ? <textarea className="form-control" rows="3" value={editing?.[field.name] ?? ''} onChange={(e) => setEditing({ ...editing, [field.name]: e.target.value })} required={!field.optional} /> : <input className="form-control" type={field.type || 'text'} min={field.min} value={editing?.[field.name] ?? ''} onChange={(e) => setEditing({ ...editing, [field.name]: e.target.value })} required={!field.optional} />}</div>)}</FormModal><ConfirmDialog show={Boolean(removeTarget)} title={`Delete ${itemName}`} message={`Delete ${removeTarget?.name}? This action cannot be undone.`} onClose={() => setRemoveTarget(null)} onConfirm={remove} busy={busy} /></>;
}
